# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ec.deep.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ec.deep.GetProductsRequest" do
  end
  add_message "ec.deep.GetProductsResponse" do
    repeated :products, :message, 1, "ec.deep.DeepProduct"
  end
  add_message "ec.deep.DeepProduct" do
    optional :id, :int32, 1
    optional :name, :string, 2
  end
end

module Ec
  module Deep
    GetProductsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ec.deep.GetProductsRequest").msgclass
    GetProductsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ec.deep.GetProductsResponse").msgclass
    DeepProduct = Google::Protobuf::DescriptorPool.generated_pool.lookup("ec.deep.DeepProduct").msgclass
  end
end
