# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ec.deep.proto for package 'ec.deep'


module Ec
  module Deep
    module ProductService
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'ec.deep.ProductService'

        rpc :GetProducts, GetProductsRequest, GetProductsResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end