# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ec.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ec.GetProductsRequest" do
  end
  add_message "ec.GetProductsResponse" do
    repeated :products, :message, 1, "ec.Product"
  end
  add_message "ec.GetByProductIdRequest" do
    optional :product_id, :int32, 1
  end
  add_message "ec.GetByProductIdResponse" do
    optional :product, :message, 1, "ec.Product"
  end
  add_message "ec.Product" do
    optional :id, :int32, 1
    optional :name, :string, 2
    optional :price, :double, 3
    optional :created_at, :string, 4
    optional :updated_at, :string, 5
    repeated :tags, :message, 6, "ec.Tag"
  end
  add_message "ec.Tag" do
    optional :id, :int32, 1
    optional :name, :string, 2
    optional :created_at, :string, 3
    optional :updated_at, :string, 4
  end
end

module Ec
  GetProductsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ec.GetProductsRequest").msgclass
  GetProductsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ec.GetProductsResponse").msgclass
  GetByProductIdRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ec.GetByProductIdRequest").msgclass
  GetByProductIdResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ec.GetByProductIdResponse").msgclass
  Product = Google::Protobuf::DescriptorPool.generated_pool.lookup("ec.Product").msgclass
  Tag = Google::Protobuf::DescriptorPool.generated_pool.lookup("ec.Tag").msgclass
end
