# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ec.proto for package 'ec'

require 'grpc'
require 'ec_pb'

module Ec
  module ProductService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'ec.ProductService'

      rpc :GetProducts, GetProductsRequest, GetProductsResponse
      rpc :GetByProductId, GetByProductIdRequest, GetByProductIdResponse
    end

    Stub = Service.rpc_stub_class
  end
end
