# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: other.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "OtherProduct" do
    optional :id, :int32, 1
    optional :name, :string, 2
  end
end

OtherProduct = Google::Protobuf::DescriptorPool.generated_pool.lookup("OtherProduct").msgclass
